fix warning with null schedules
Puppet was still trying to start the incr timers:

Error: Systemd start for pgbackrest-backup-incr@weather-01.timer failed!
journalctl log for pgbackrest-backup-incr@weather-01.timer:
Feb 12 21:43:14 backup-storage-01 systemd[1]: pgbackrest-backup-incr@weather-01.timer: Timer unit lacks value setting. Refusing.

... because the incr thing *is* in the key.