fix crash without exported resources
This was working in production for us because we already had config
object that were creating the parent directory, this crashes
otherwise with:

Error: /Stage[main]/Pgbackrest::Config/File[/etc/pgbackrest/conf.d]/ensure: change from 'absent' to 'directory' failed: Cannot create /etc/pgbackrest/conf.d; parent directory /etc/pgbackrest does not exist